// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { env } from "@/config";
import "dotenv/config";
import process from "node:process";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env.databaseUrl ?? (() => {
      throw new Error("DATABASE_URL is not set");
    })(),
  },
});
